# Generated by Django 5.1.3 on 2024-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='bed_statuses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('partially_occupied', 'Partially Occupied'), ('fully_occupied', 'Fully Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20),
        ),
    ]
