# Generated by Django 5.1.3 on 2024-12-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0002_ward_bed_statuses_ward_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='bed_statuses',
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=50)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='bed_management.ward')),
            ],
        ),
    ]
