# Generated by Django 5.1.3 on 2024-12-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0003_remove_ward_bed_statuses_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='status',
        ),
        migrations.AlterField(
            model_name='bed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
