# Generated by Django 5.1.3 on 2024-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0004_remove_ward_status_alter_bed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('partially_occupied', 'Partially Occupied'), ('fully_occupied', 'Fully Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
