# Generated by Django 5.1 on 2024-12-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
