# Generated by Django 5.1.3 on 2024-11-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hosp_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('hosp_name', models.CharField(max_length=255)),
                ('hosp_email', models.EmailField(max_length=254, unique=True)),
                ('hosp_contact_no', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('hosp_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hosp_log', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hosp_address', models.TextField()),
                ('hosp_no_of_beds', models.IntegerField()),
                ('hosp_password', models.CharField(max_length=255)),
            ],
        ),
    ]
