# Generated by Django 5.1.3 on 2024-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hospital_options_hospital_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hosp_password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
    ]
