# Generated by Django 5.1.4 on 2024-12-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_items_sales_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='inventory',
        ),
        migrations.AddField(
            model_name='sales',
            name='items',
            field=models.ManyToManyField(through='inventory.SalesItem', to='inventory.inventory'),
        ),
    ]
