# Generated by Django 5.1.4 on 2024-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_inv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='items',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Inv_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
