# Generated by Django 5.1.4 on 2024-12-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_sales_items_alter_inventory_inv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
