# Generated by Django 5.1.4 on 2024-12-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='expiry_date',
        ),
    ]
