# Generated by Django 5.1.4 on 2024-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventory_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expiry_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
